#!/usr/bin/env sh

monitor_left="HDMI-2"
monitor_right="HDMI-1-1"

xrandr \
    --output $monitor_left \
    --auto \
    --primary

xrandr \
    --output $monitor_right \
    --auto \
    --right-of $monitor_left

unset monitor_left
unset monitor_right

feh --bg-max --randomize ~/pictures/wallpapers/* &
xdotool key Num_Lock

exec i3 --shmlog-size=26214400
