#!/usr/bin/env sh

if [[ "$0" == "help" ]]; then
    echo "usage: docker-login <profile> [<region>]"
    echo ""
    echo "Args:"
    echo "  profile    AWS profile"
    echo "  region     AWS region (default: 'sa-east-1')"
    exit 0
fi

profile="$1"
if [[ "$profile" == "" ]]; then
    echo "\033[0;31mERRO: expected value for argument 'profile'\033[0m" >&2
    exit 1
fi

region="$2"
if [[ "$region" == "" ]]; then
    echo "\033[0;33mWARN: no value for argument 'region', using default ('sa-east-1')\033[0m"
    region="sa-east-1"
fi

$(aws ecr get-login --no-include-email --profile $profile --region  $region)

unset profile
unset region
